JDP230601-5
piotr-grosicki/project-jdp-2306-01 pull request #2
Opened 2023-06-02 23:01 UTC by ZuzannJanik

### Jira ticket:  JDP230601-5 
https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=217&projectKey=JDP230601&view=detail&selectedIssue=JDP230601-5

### What has changed:
- Changing dependencies permanently from fixed with appointments
- Introduction of package structure
- Initialization of the UserController class

### What reviewers should know:
nothing

2023-06-03 10:37 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2023-06-04 07:38 UTC, piotr-grosicki requested changes

2023-06-04 07:38 UTC, piotr-grosicki commented on build.gradle
> -    runtimeOnly('com.h2database:h2')
h2 musi zostac, nie moze zostac usunieta poniewaz testy z niej korzystaja

2023-06-04 07:38 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public void createUser(UserDto userDto) {
RequestBody

2023-06-04 07:38 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public UserDto blockUser(UserDto userDto) {
RequestBody

2023-06-04 07:38 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public void generateToken(UserDto userDto) {
RequestBody

2023-06-04 07:38 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public  void deleteUser(Long userId) {
PathVariable

2023-06-05 01:13 UTC, ZuzannJanik commented on build.gradle
> -    runtimeOnly('com.h2database:h2')
ok

2023-06-05 01:13 UTC, ZuzannJanik commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public void createUser(UserDto userDto) {
ok

2023-06-05 01:13 UTC, ZuzannJanik commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public UserDto blockUser(UserDto userDto) {
ok

2023-06-05 01:14 UTC, ZuzannJanik commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public void generateToken(UserDto userDto) {
ok

2023-06-05 01:14 UTC, ZuzannJanik commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public  void deleteUser(Long userId) {
ok

2023-06-05 06:38 UTC, merged