Config
piotr-grosicki/project-jdp-2306-01 pull request #3
Opened 2023-06-02 23:10 UTC by pawelecmateusz

Konfiguracja plików:

application.properties
allowPublicKeyRetrieval=true

config.yml
image: cimg/openjdk:17.0.6

build.gradle
wersje pluginów i dodanie zależności

gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-bin.zip

2023-06-03 06:11 UTC, konradpieczynski requested changes
Do zmiany:
spring.datasource.password=kodilla_Pass123

2023-06-03 06:33 UTC, pawelecmateusz commented
> Do zmiany:
> spring.datasource.password=kodilla_Pass123

Utwórz bazę danych i użytkownika zgodnie z danymi zapisanymi w pliku application.properties.

spring.datasource.username=kodilla_user
spring.datasource.password=kodilla_password

2023-06-03 10:35 UTC, konradpieczynski commented
punkt który wykonywałem ma zmienione na kodilla_Pass123 i jest na bazie tego commita. Więc i tak się zmieni :)

2023-06-03 10:38 UTC, piotr-grosicki requested changes

2023-06-03 10:38 UTC, piotr-grosicki commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/kodilla_project?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
w testach wszystko bylo OK, przez te zmiane niemozliwe bedzie uruchomienie aplikacji na circleci.

test/resources/application.properties nie ruszamy :)

2023-06-03 10:38 UTC, piotr-grosicki commented on build.gradle
> -    runtimeOnly('com.h2database:h2')
ta baza musi zostac (jako dodatkowa obok mysql) pod testy

2023-06-04 07:39 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2023-06-05 06:39 UTC, closed without merging