Jdp230601 15
piotr-grosicki/project-jdp-2306-01 pull request #4
Opened 2023-06-03 01:21 UTC by ZuzannJanik

### Jira ticket: Jdp230601 15
https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=217&projectKey=JDP230601&view=detail&selectedIssue=JDP230601-15

### What has changed:
- I created a User entity with variables
- I defined a dependency with entity Cart

### What reviewers should know:
I created the variables based on the established scheme. However, it seems that the token validation variable may be different depending on the token validation method used.

2023-06-03 10:37 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2023-06-05 06:39 UTC, piotr-grosicki commented
konflikty, https://www.jetbrains.com/help/idea/resolving-conflicts.html

2023-06-08 12:56 UTC, ZuzannJanik commented
Konflikty naprawione

2023-06-08 15:38 UTC, konradpieczynski requested changes
Nie potrzebnie dodana linijka w build.gradle

2023-06-08 15:38 UTC, konradpieczynski commented on build.gradle
Nie potrzebne.

2023-06-09 00:17 UTC, ZuzannJanik commented on build.gradle
Usunięte.

2023-06-09 04:56 UTC, konradpieczynski approved these changes

2023-06-09 15:17 UTC, merged